import type {Metadata} from 'next';
import {Poppins} from 'next/font/google';

// eslint-disable-next-line new-cap
const poppins = Poppins({subsets: ['latin'], weight: '400'});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='./credit-card.ico' sizes='any' />
				<title>Credit4Card</title>
			</head>
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
